### ISSUE TITLE
Why doesn't package.json have version?

### ISSUE THREAD

**Issue by bahmutov** [semantic-release/release-notes-generator-v3#6]
For example npm refuses to install it from github reference
```
npm i -D dfbaskin/release-notes-generator#f51446db9ea47b484f5155e87fe7a19418695e8e
npm ERR! No version provided in package.json
```

**Comment by gr2m** [comment]
this is resolved now as semantic-release-cli defaults to a placeholder version. Let me know if one of the packages is still lacking a version placeholder today
